### ISSUE TITLE
`isahc::response::text::Text<'_>` does not implement `Send` for `async-std::task::spawn`

### ISSUE THREAD

**Issue by Earthson** [sagebind/isahc#173]
```rust
use async_std::task;
use std;
use isahc::prelude::*;
use isahc::{RequestExt, ResponseExt};


async fn get_url<T: ToString>(addr: T, timeout: u64) {
    let res = Request::get(addr.to_string())
        .header("Accept-Encoding", "gzip")
        .header("User-Agent", "(KHTML, like Gecko) Chrome/54.0.2840.100 ")
        .timeout(std::time::Duration::from_millis(timeout))
        .body(()).unwrap()
        .send_async().await.unwrap()
        .text_async().await.unwrap();
    println!("{:?}", res);
}


fn main() {
    //task::block_on(get_url("https://httpbin.org/json", 6000)); //works
    task::block_on(task::spawn(get_url("https://httpbin.org/json", 6000))); //failed
}
```

```bash
error: future cannot be sent between threads safely
  --> src/test.rs:20:20
   |
20 |     task::block_on(task::spawn(get_url("https://httpbin.org/json", 6000)));
   |                    ^^^^^^^^^^^ future returned by `get_url` is not `Send`
   |
   = help: the trait `std::marker::Send` is not implemented for `dyn std::future::Future<Output = std::result::Result<std::string::String, std::io::Error>>`
note: future is not `Send` as this value is used across an await
  --> src/test.rs:8:15
   |
8  |       let res = Request::get(addr.to_string())
   |  _______________^
9  | |         .header("Accept-Encoding", "gzip")
10 | |         .header("User-Agent", "(KHTML, like Gecko) Chrome/54.0.2840.100 ")
11 | |         .timeout(std::time::Duration::from_millis(timeout))
12 | |         .body(()).unwrap()
13 | |         .send_async().await.unwrap()
14 | |         .text_async().await.unwrap();
   | |                     ^               - `Request::get(addr.to_string())
        .header("Accept-Encoding", "gzip")
        .header("User-Agent", "(KHTML, like Gecko) Chrome/54.0.2840.100 ")
        .timeout(std::time::Duration::from_millis(timeout))
        .body(()).unwrap()
        .send_async().await.unwrap()
        .text_async()` is later dropped here
   | |                     |
   | |_____________________await occurs here, with `Request::get(addr.to_string())
        .header("Accept-Encoding", "gzip")
        .header("User-Agent", "(KHTML, like Gecko) Chrome/54.0.2840.100 ")
        .timeout(std::time::Duration::from_millis(timeout))
        .body(()).unwrap()
        .send_async().await.unwrap()
        .text_async()` maybe used later
   |                       has type `isahc::response::text::Text<'_>`

error: aborting due to previous error
```

**Comment by sagebind** [comment]
The reason that `Text` does not implement `Send` currently is that we do not know if the `T` in `Response<T>` implements send or not. In practice `T = Body` and `Body: Send` though. I'll see what I can do to improve this.

**Comment by sagebind** [comment]
This should now work in version 0.9.1!
